{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.gatewayFullname" . }}
  labels:
    {{- include "loki.gatewayLabels" . | nindent 4 }}
    {{- with .Values.gateway.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  {{- with .Values.gateway.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if and (eq "LoadBalancer" .Values.gateway.service.type) .Values.gateway.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gateway.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      {{- if and (eq "NodePort" .Values.gateway.service.type) .Values.gateway.service.nodePort }}
      nodePort: {{ .Values.gateway.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "loki.gatewaySelectorLabels" . | nindent 4 }}
{{- end }}
