---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-loki-grafana-com-v1-alertingrule
  failurePolicy: Fail
  name: valertingrule.loki.grafana.com
  rules:
  - apiGroups:
    - loki.grafana.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alertingrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-loki-grafana-com-v1-lokistack
  failurePolicy: Fail
  name: vlokistack.loki.grafana.com
  rules:
  - apiGroups:
    - loki.grafana.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lokistacks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-loki-grafana-com-v1-recordingrule
  failurePolicy: Fail
  name: vrecordingrule.loki.grafana.com
  rules:
  - apiGroups:
    - loki.grafana.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - recordingrules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-loki-grafana-com-v1-rulerconfig
  failurePolicy: Fail
  name: vrulerconfig.loki.grafana.com
  rules:
  - apiGroups:
    - loki.grafana.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rulerconfigs
  sideEffects: None
