resources:
- ../../crd
- ../../rbac
- ../../manager
- ./minio

# Adds namespace to all resources.
namespace: default

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue
commonLabels:
  app.kubernetes.io/name: loki-operator
  app.kubernetes.io/instance: loki-operator-v0.0.1
  app.kubernetes.io/version: "0.0.1"
  app.kubernetes.io/part-of: loki-operator
  app.kubernetes.io/managed-by: operator-lifecycle-manager

patchesStrategicMerge:
- manager_related_image_patch.yaml
- manager_run_flags_patch.yaml
