# Meta Data for SEO

## Homepage
title = "Loki Operator"
titleSeparator = "-"
titleAddition = "Kubernetes Operator for Loki"
description = "A Kubernetes Operator for Loki provided by the Grafana Loki SIG operator. "

## Open Graph + Twitter Cards
images = ["logo.png"]
#twitterSite = ""
#twitterCreator = ""
#facebookAuthor = ""
#facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo.png"
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/grafana"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and based on <a href=\"https://getdoks.org/\">Doks</a>"

# Edit Page
docsRepo = "https://github.com/grafana/loki"
editPage = false

[options]
  lazySizes = false
  clipBoard = true
  instantPage = false
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = true
  highLight = false
  kaTex = false