# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/cortexproject/cortex"
  source = "https://github.com/grafana/cortex"
  branch = "lazy-load-chunks"

[[constraint]]
  name = "github.com/weaveworks/common"
  branch = "master"

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "github.com/uber/jaeger-lib"
  version = "2.0.0"

[[override]]
  name = "github.com/uber/jaeger-client-go"
  branch = "master"

# For Prometheus

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/prometheus"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[override]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[override]]
  name = "github.com/prometheus/tsdb"
  version = "0.6.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/hpcloud/tail"
  source = "github.com/grafana/tail"
  branch = "master"
