kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Ingress Controller Web Port
  - containerPort: 8080
    hostPort: 8080
  # Ingress Controller Web Secure Port
  - containerPort: 8443
    hostPort: 8443
  # Ingress Controller Admin Port
  - containerPort: 8081
    hostPort: 8081
