kind: ServiceAccount
apiVersion: v1
metadata:
  name: log-file-metric-exporter
secrets:
  - name: logfile-metric-dockercfg
  - name: logfile-metric-token
imagePullSecrets:
  - name: logfile-metric-dockercfg
