kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: log-file-metric-exporter-privileged-binding
subjects:
  - kind: ServiceAccount
    name: log-file-metric-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-file-metric-exporter-privileged
