apiVersion: v1
kind: Service
metadata:
  name: log-file-metric-exporter-metrics
  labels:
    name: log-file-metric-exporter
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: log-file-metric-exporter-metrics
spec:
  ports:
    - name: logfile-metrics
      port: 2112
      protocol: TCP
      targetPort: logfile-metrics
  selector:
    name: log-file-metric-exporter
