apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
          - name: RELATED_IMAGE_LOKI
            value: docker.io/grafana/loki:3.3.2
          - name: RELATED_IMAGE_GATEWAY
            value: quay.io/observatorium/api:latest
          - name: RELATED_IMAGE_OPA
            value: quay.io/observatorium/opa-openshift:latest
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
        - name: kube-rbac-proxy
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
