{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if and $isDistributed (gt (int .Values.patternIngester.replicas) 1) }}
apiVersion: {{ include "loki.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.patternIngesterFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.patternIngesterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.patternIngesterSelectorLabels" . | nindent 6 }}
  {{- with .Values.patternIngester.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
