---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: distributor
  name: loki-distributor-http
spec:
  ports:
  - name: metrics
    port: 3100
    targetPort: 3100
  selector:
    app.kubernetes.io/component: distributor
