apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: config.loki.grafana.com/v1
    kind: ProjectConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: loki-operator.grafana.com
    featureGates:
      lokiStackGateway: true
      restrictedPodSecurityStandard: false
      #
      # Webhook feature gates
      #
      lokiStackWebhook: true
      alertingRuleWebhook: true
      recordingRuleWebhook: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: loki-operator-v0.7.1
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: loki-operator
    app.kubernetes.io/version: 0.7.1
  name: loki-operator-manager-config
