apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "loki.fullname" . }}
  labels:
    app: {{ template "loki.name" . }}
    chart: {{ template "loki.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.loki.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.loki.replicas }}
  selector:
    matchLabels:
      app: {{ template "loki.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.loki.deploymentStrategy }}
  {{- if ne .Values.loki.deploymentStrategy "RollingUpdate" }}
    rollingUpdate: null
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "loki.name" . }}
        name: {{ template "loki.name" . }}
        release: {{ .Release.Name }}
{{- with .Values.loki.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "loki.serviceAccountName" . }}
{{- if .Values.loki.priorityClassName }}
      priorityClassName: {{ .Values.loki.priorityClassName }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: "/data"
              subPath: {{ .Values.loki.persistence.subPath }}
          ports:
            - name: {{ template "loki.name" . }}-metrics
              containerPort: {{ .Values.loki.service.port }}
              protocol: TCP
{{- with .Values.loki.livenessProbe }}
          livenessProbe:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.loki.readinessProbe }}
          readinessProbe:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.loki.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
    {{- with .Values.loki.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.loki.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.loki.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "loki.fullname" . }}
        - name: storage
      {{- if .Values.loki.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.loki.persistence.existingClaim | default (include "loki.fullname" .) }}
      {{- else }}
          emptyDir: {}
      {{- end -}}
