{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.bloomBuilderFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.bloomBuilderLabels" . | nindent 4 }}
    {{- with .Values.bloomBuilder.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.loki.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
      {{- if .Values.bloomBuilder.appProtocol.grpc }}
      appProtocol: {{ .Values.bloomBuilder.appProtocol.grpc }}
      {{- end }}
    - name: grpclb
      port: 9096
      targetPort: grpc
      protocol: TCP
      {{- if .Values.bloomBuilder.appProtocol.grpc }}
      appProtocol: {{ .Values.bloomBuilder.appProtocol.grpc }}
      {{- end }}
  selector:
    {{- include "loki.bloomBuilderSelectorLabels" . | nindent 4 }}
{{- end -}}
