{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if $isDistributed }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.indexGatewayFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.indexGatewayLabels" . | nindent 4 }}
    {{- with .Values.indexGateway.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.loki.serviceAnnotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
    {{- with .Values.indexGateway.serviceAnnotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
spec:
  type: {{ .Values.indexGateway.serviceType }}
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
      {{- with .Values.indexGateway.appProtocol.grpc }}
      appProtocol: {{ . }}
      {{- end }}
  selector:
    {{- include "loki.indexGatewaySelectorLabels" . | nindent 4 }}
{{- with .Values.indexGateway.trafficDistribution | default .Values.loki.service.trafficDistribution }}
  trafficDistribution: {{ . }}
{{- end }}
{{- end }}
