apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  endpoint: http://minio.default.svc:9000
  bucketnames: loki
  access_key_id: minio
  access_key_secret: minio123
type: Opaque
