# permissions for end users to view recordingrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recordingrule-viewer-role
rules:
- apiGroups:
  - loki.grafana.com
  resources:
  - recordingrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loki.grafana.com
  resources:
  - recordingrules/status
  verbs:
  - get
