# permissions for end users to view rulerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rulerconfig-viewer-role
rules:
- apiGroups:
  - loki.grafana.com
  resources:
  - rulerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loki.grafana.com
  resources:
  - rulerconfigs/status
  verbs:
  - get
