apiVersion: config.loki.grafana.com/v1
kind: ProjectConfig
health:
  healthProbeBindAddress: :8081
metrics:
  # Bind only on this host to allow accessing metrics
  # only via the kube-rbac-proxy sidecar.
  bindAddress: 127.0.0.1:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: loki-operator.grafana.com
featureGates:
  #
  # Monitoring feature gates
  #
  serviceMonitors: true
  serviceMonitorTlsEndpoints: true
  lokiStackAlerts: true
  #
  # Encryption feature gates
  #
  httpEncryption: true
  grpcEncryption: true
  builtInCertManagement:
    enabled: true
    # CA certificate validity: 5 years
    caValidity: 43830h
    # CA certificate refresh at 80% of validity
    caRefresh: 35064h
    # Target certificate validity: 90d
    certValidity: 2160h
    # Target certificate refresh at 80% of validity
    certRefresh: 1728h
  #
  # Component feature gates
  #
  lokiStackGateway: true
  grafanaLabsUsageReport: false
  restrictedPodSecurityStandard: true
  defaultNodeAffinity: true
  #
  # Webhook feature gates
  #
  lokiStackWebhook: true
  alertingRuleWebhook: true
  recordingRuleWebhook: true
  rulerConfigWebhook: true
  #
  # OpenShift feature gates
  #
  openshift:
    enabled: true
    servingCertsService: true
    ruleExtendedValidation: true
    clusterTLSPolicy: true
    clusterProxy: true
    dashboards: true
