apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: loki-operator
  name: metrics-monitor
spec:
  endpoints:
    - path: /metrics
      targetPort: 8443
      scheme: https
      interval: 30s
      scrapeTimeout: 10s
      authorization:
        type: bearer
        credentials:
          key: token
          name: loki-operator-controller-manager-metrics-token
      tlsConfig:
        ca:
          secret:
            key: service-ca.crt
            name: loki-operator-controller-manager-metrics-token
        serverName: loki-operator-controller-manager-metrics-service.openshift-operators-redhat.svc
