{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if and $isDistributed (gt (int .Values.ingester.replicas) 1) (.Values.ingester.zoneAwareReplication.enabled) }}
{{- if kindIs "invalid" .Values.ingester.maxUnavailable }}
{{- fail "`.Values.ingester.maxUnavailable` must be set when `.Values.ingester.replicas` is greater than 1." }}
{{- else }}
apiVersion: {{ include "loki.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.ingesterFullname" . }}-rollout
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.ingesterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      rollout-group: {{ include "loki.prefixRolloutGroup" . }}ingester
  {{- with .Values.ingester.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
