version: "3.3"
services:
  backend:
    build:
      context: ../../
      dockerfile: ./cmd/logql-analyzer/Dockerfile
    entrypoint: [ "/usr/bin/logql-analyzer", "--server.http-listen-port=3001" ]
    ports:
      - "3001:3001"

  docs:
    image: grafana/docs-base:latest
    volumes:
      - ../../docs/sources:/hugo/content/docs/loki/latest
    ports:
      - "3002:3002"
