{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if and $isDistributed .Values.ruler.enabled }}
{{- range $dir, $files := .Values.ruler.directories }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.rulerFullname" $ }}-{{ include "loki.rulerRulesDirName" $dir }}
  labels:
    {{- include "loki.rulerLabels" $ | nindent 4 }}
data:
  {{- toYaml $files | nindent 2}}
{{- end }}
{{- end }}
