{{- if .Values.tableManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.tableManagerFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.tableManagerLabels" . | nindent 4 }}
  annotations:
    {{- with .Values.loki.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.tableManager.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.loki.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "loki.tableManagerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "loki.configMapOrSecretContentHash" (dict "ctx" . "name" "/config.yaml") }}
        {{- with .Values.loki.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tableManager.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "loki.tableManagerSelectorLabels" . | nindent 8 }}
        {{- with .Values.loki.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tableManager.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "loki.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "loki.tableManagerPriorityClassName" . | nindent 6 }}
      securityContext:
        {{- include "loki.podSecurityContext" . | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.tableManager.terminationGracePeriodSeconds }}
      {{- if and (semverCompare ">=1.33-0" (include "loki.kubeVersion" .)) (kindIs "bool" .Values.tableManager.hostUsers) }}
      hostUsers: {{ .Values.tableManager.hostUsers }}
      {{- end }}
      containers:
        - name: table-manager
          image: {{ include "loki.image" . }}
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          args:
            - -config.file=/etc/loki/config/config.yaml
            - -target=table-manager
            {{- with (concat .Values.global.extraArgs .Values.tableManager.extraArgs) | uniq }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.loki.server.http_listen_port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.loki.server.grpc_listen_port }}
              protocol: TCP
          {{- with .Values.tableManager.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tableManager.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.loki.containerSecurityContext | nindent 12 }}
          {{- with .Values.loki.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.loki.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            {{- if .Values.enterprise.enabled }}
            - name: license
              mountPath: /etc/loki/license
            {{- end }}
            {{- with (concat .Values.global.extraVolumeMounts .Values.tableManager.extraVolumeMounts) | uniq }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.tableManager.resources | nindent 12 }}
        {{- if .Values.tableManager.extraContainers }}
        {{- toYaml .Values.tableManager.extraContainers | nindent 8}}
        {{- end }}
      {{- with .Values.tableManager.affinity }}
      affinity:
        {{- tpl ( . | toYaml) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tableManager.dnsConfig | default .Values.loki.dnsConfig }}
      dnsConfig:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tableManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tableManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- include "loki.configVolume" . | nindent 10 }}
        {{- if .Values.enterprise.enabled }}
        - name: license
          secret:
          {{- if .Values.enterprise.useExternalLicense }}
            secretName: {{ .Values.enterprise.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        {{- end }}
        {{- with (concat .Values.global.extraVolumes .Values.tableManager.extraVolumes) | uniq }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
