apiVersion: config.loki.grafana.com/v1
kind: ProjectConfig
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: :8080
webhook:
  port: 9443
leaderElection:
  leaderElect: false
  resourceName: e3716011.grafana.com
featureFlags:
  enableLokiStackGateway: true
  enableTLSGRPCServices: true
  enableLokiStackWebhook: false
  enableAlertingRuleWebhook: false
  enableRecordingRuleWebhook: false
