apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: loki-operator-controller-manager-metrics-reader
  labels:
    app.kubernetes.io/instance: loki-operator-v0.7.1
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: loki-operator
    app.kubernetes.io/version: 0.7.1
  name: loki-operator-controller-manager-metrics-token
type: kubernetes.io/service-account-token
