apiVersion: loki.openshift.io/v1beta1
kind: LokiStack
metadata:
  name: lokistack-sample
spec:
  size: 1x.small
  replicationFactor: 2
  storage:
    secret:
      name: test
  storageClassName: standard
