{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if and $isDistributed (not .Values.indexGateway.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.querierFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.querierSelectorLabels" . | nindent 4 }}
    prometheus.io/service-monitor: "false"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
      {{- if .Values.querier.appProtocol.grpc }}
      appProtocol: {{ .Values.querier.appProtocol.grpc }}
      {{- end }}
  selector:
    {{- include "loki.querierSelectorLabels" . | nindent 4 }}
{{- end }}
