apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: config.loki.grafana.com/v1
    kind: ProjectConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      # Bind only on this host to allow accessing metrics
      # only via the kube-rbac-proxy sidecar.
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: false
      resourceName: e3716011.grafana.com
    bundleType: openshift
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: cluster-logging
    app.kubernetes.io/version: 0.0.1
  name: loki-operator-manager-config
