{{- $isDistributed := eq (include "loki.deployment.isDistributed" .) "true" -}}
{{- if and $isDistributed .Values.overridesExporter.enabled (gt (int .Values.overridesExporter.replicas) 1) }}
{{- if kindIs "invalid" .Values.overridesExporter.maxUnavailable }}
{{- fail "`.Values.overridesExporter.maxUnavailable` must be set when `.Values.overridesExporter.replicas` is greater than 1." }}
{{- else }}
apiVersion: {{ include "loki.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loki.overridesExporterFullname" . }}
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "loki.overridesExporterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.overridesExporterSelectorLabels" . | nindent 6 }}
  {{- with .Values.overridesExporter.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
