name: Checks
on: [push]
jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      BUILD_IN_CONTAINER: false 
    container:
      image: grafana/loki-build-image:0.31.3
    steps:
      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: make lint
      - run: make check-doc
      - run: make check-mod
      - run: make validate-example-configs
      - run: make check-example-config-doc
      - run: make check-drone-drift
      - run: make check-generated-files
      - run: make test
