name: Promtail Windows Test
on:
  pull_request:
    branches: ["main", "k*", "release-[0-9]+.[0-9]+.x"]
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']
    branches: ["main", "k*", "release-[0-9]+.[0-9]+.x"]
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    strategy:
      matrix:
        go-version: [ '1.22.2', '1.23.1' ]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Run promtail tests
        run: go test .\clients\pkg\promtail\targets\windows\... -v
