name: Verify release workflow updates
on: [pull_request]
jobs:
  check-release-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
    - name: setup jsonnet
      run: |
        go install github.com/google/go-jsonnet/cmd/jsonnet@v0.20.0
        go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@v0.5.1
    - name: Check that the release workflows have been updated properly
      run: |
          make BUILD_IN_CONTAINER=false release-workflows-check
